# Exported from Render on 2024-05-22T06:11:02Z
databases:
  - name: collective_blog
    databaseName: collective_blog
    user: serhii
    plan: free

services:
  - type: web
    name: collective_blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collective_blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default